/**==============================================================================
 * clinic JSC (www.clinic.vn) Proprietary.
 * Copyright 2015 clinic JSC.
 * UNPUBLISHED WORK
 * ALL RIGHTS RESERVED
 *
 * This software is the confidential and proprietary information of 
 * clinic J.S.C ("Proprietary Information").  Any use, reproduction,
 * distribution or disclosure of the software or Proprietary Information,
 * in whole or in part, must comply with the terms of the license  
 * agreement, nondisclosure agreement or contract entered into with 
 * clinic providing access to this software.
 *
 * Project name  : clinic-api<br>
 * File name     : AbsService.java<br>
 * <p>
 * Changes History <br>
 *		Date				Person				Reason<br>
 *		Aug 20, 2015		daiql				Initial<br>
 * </p>
 *
 * @author daiql
 *=============================================================================*/
package com.clinic.clinic.api.bizlogic.service.impl;

import java.util.UUID;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.clinic.clinic.common.exception.BizlogicException;

/**
 * <p>
 * The basic abstract business logic service.
 * </p>
 *
 * @author daiql<br>
 * @version 1.0<br>
 */
public abstract class AbsService {
    /** Logging property. */
    private static final Logger LOGGER = LoggerFactory.getLogger(AbsService.class);
    
    /**
     * <p>Create a new business logic exception and throws it to caller.</p>
     *
     * @param msgKey {@link String} system message key, should be got from message's constants
     * @param params list of parameter's value will be used in localized message
     */
    protected void throwBizlogicException(final String msgKey, final String... params) {
        final BizlogicException bizException = new BizlogicException(msgKey);
        if (null != params && params.length > 0) {
            for (final String param : params) {
                bizException.addParamValue(param);
            }
        }
        throw bizException;
    }
    
    /**
     * 
     * <p>Get UUID generated by database. Use this value to set into initial code</p>
     *
     * @return
     *
     */
    String getUUID() {
        return UUID.randomUUID().toString();
    }
}
