/**==============================================================================
 * clinic JSC (www.clinic.vn) Proprietary.
 * Copyright 2015 clinic JSC.
 * UNPUBLISHED WORK
 * ALL RIGHTS RESERVED
 *
 * This software is the confidential and proprietary information of 
 * clinic J.S.C ("Proprietary Information").  Any use, reproduction,
 * distribution or disclosure of the software or Proprietary Information,
 * in whole or in part, must comply with the terms of the license  
 * agreement, nondisclosure agreement or contract entered into with 
 * clinic providing access to this software.
 *
 * Project name  : clinic-api<br>
 * File name     : AbsService.java<br>
 * <p>
 * Changes History <br>
 *		Date				Person				Reason<br>
 *		Aug 20, 2015		daiql				Initial<br>
 * </p>
 *
 * @author daiql
 *=============================================================================*/
package com.clinic.clinic.api.bizlogic.service.impl;

import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.UUID;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;

import com.clinic.clinic.common.consts.IBizErrorCode;
import com.clinic.clinic.common.consts.IConstants;
import com.clinic.clinic.common.exception.BizlogicException;

/**
 * <p>
 * The basic abstract business logic service.
 * </p>
 *
 * @author daiql<br>
 * @version 1.0<br>
 */
public abstract class AbsService {
    /** Logging property. */
    private static final Logger LOGGER = LoggerFactory.getLogger(AbsService.class);
    
    /**
     * <p>Create a new business logic exception and throws it to caller.</p>
     *
     * @param msgKey {@link String} system message key, should be got from message's constants
     * @param params list of parameter's value will be used in localized message
     */
    protected void throwBizlogicException(final int httpCode, final int bizCode, final String msgKey, final Object... params) {
        BizlogicException.throwEx(httpCode, bizCode, msgKey, params);
    }
    
    protected void throwBizlogicException(final HttpStatus httpStatus, final int bizCode, final String msgKey, final Object... params) {
    	this.throwBizlogicException(httpStatus.value(), bizCode, msgKey, params);
    }
    
    protected void throwBizlogicException(final String msgKey, final Object... params) {
    	this.throwBizlogicException(500, IBizErrorCode.UNKNOWN_ERROR, msgKey, params);
    }
    
    /**
     * 
     * <p>Get UUID generated by database. Use this value to set into initial code</p>
     *
     * @return
     *
     */
    String getUUID() {
        return UUID.randomUUID().toString();
    }
    
    protected String getHashedText(String plainText) throws BizlogicException {
        if(LOGGER.isDebugEnabled()) {
            LOGGER.debug(IConstants.BEGIN_METHOD);
        }
        String retVal = null;
        try {
            MessageDigest m;
            m = MessageDigest.getInstance("MD5");
            m.reset();
            m.update(plainText.getBytes());
            byte[] digest = m.digest();
            BigInteger bigInt = new BigInteger(1, digest);
            String hashText = bigInt.toString(16);

            // zero pad to have the full 32 chars.
            StringBuilder sb = new StringBuilder();
            sb.append(hashText);
            while (sb.length() < 32) {
                sb.insert(0, "0");
            }
            retVal = sb.toString();
        } catch (NoSuchAlgorithmException e) {
            LOGGER.error("Exception", e);
            throwBizlogicException(500, IBizErrorCode.UNKNOWN_ERROR, e.getMessage());
        } finally {
            if(LOGGER.isDebugEnabled()) {
                LOGGER.debug(IConstants.END_METHOD);
            }
        }
        return retVal;
    }

}
